# Generated by Django 5.2.17 on 2026-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portofolio/photo/'),
        ),
    ]
