# Generated by Django 5.2.17 on 2026-09-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Learning', 'learning'), ('Competent', 'competent')], default='Learning', max_length=25)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
