# Generated by Django 5.2.17 on 2026-09-13 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
