# Generated by Django 5.2.17 on 2026-09-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_techstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='experience',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
