# Generated by Django 5.2.17 on 2026-09-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_experience_thumbnail_alter_experience_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='level',
            field=models.CharField(choices=[('Technical', 'technical'), ('Soft Skill', 'soft'), ('Tool', 'tool')], default='Technical', max_length=25),
        ),
    ]
