# Generated by Django 5.2.17 on 2026-09-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_techstack_description_alter_techstack_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techstack',
            old_name='level',
            new_name='category',
        ),
    ]
