# Generated by Django 5.2.17 on 2026-09-26 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_techstack_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
